### PR TITLE
Updated Partners section

### PR DESCRIPTION
**Pull request by lindsayzhng**
Revamped the partners section- not entirely up to date to current handoff

### CODE REVIEW

**Comment by lucywang-lw** [comment]
Looks great, could you change a few minor things:
1. Remove space before & after the Our Partners section. You probably have to give CSS to the first and second `our-partners-container`s. 
image
2. Change the padding and font size on mobile screens. I'll update the PR in a bit to do it for the second box.
image

**Review by lucywang-lw — APPROVED** [review]
Great work!

**Review by lucywang-lw — CHANGES_REQUESTED** [review]
Oops I meant to approve another PR, this one needs changes - see comment above :)

**Comment by lindsayzhng** [comment]
> Looks great, could you change a few minor things:
> 
> 1. Remove space before & after the Our Partners section. You probably have to give CSS to the first and second `our-partners-container`s.
>    image
> 2. Change the padding and font size on mobile screens. I'll update the PR in a bit to do it for the second box.
>    image

fixed!

**Pull request merged**
